### ISSUE TITLE
[bug-website module] Batoto

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD2#590] opened 2021-06-13 15:59 UTC
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Windows 10 64 Bit

**Describe the bug**
Can't do anything on Batoto (no manga info, chapter list, or download). it's been like that for quite some time.

**Additional context**
seems like it is because of a new cloudflare challenge

**Log**
17:58:08:594 WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://bato.to/series/69080

**Comment by Slasar41** [comment] 2021-06-14 10:05
Duplicate of https://github.com/dazedcat19/FMD2/issues/467.

**Closed as completed by Slasar41** 2021-06-14 10:05 UTC
