### ISSUE TITLE
[Website module report] mangas.in no load list manga (MangAs.lua)

### ISSUE THREAD

**Issue by manhwalover** [dazedcat19/FMD2#472] opened 2021-04-04 19:48 UTC
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7

**Website Information**
* **Name: Mangas** 
* **Root URL: https://mangas.in/**
* **Directory list URL: https://mangas.in/manga-list**

* **Example manga info URL: https://mangas.in/manga/aire**
* **Example chapter URL: https://mangas.in/manga/aire/10-34u41**

**Languages**
Spanish

**Describe the bug**
After **update manga list**, cannot load manga in box list
![image](https://user-images.githubusercontent.com/79884368/113644503-1f175c80-96af-11eb-81ab-695a01db8228.png)

**Comment by Slasar41** [comment] 2021-04-08 19:16
Duplicate of https://github.com/dazedcat19/FMD2/issues/86

**Closed as completed by Slasar41** 2021-04-08 19:16 UTC

**Comment by manhwalover** [comment] 2021-04-09 09:12
Okay, It seems like this is a complicated and unsolved case
