### ISSUE TITLE
[bug-GManga module]

### ISSUE THREAD

**Issue by mjeed02** [dazedcat19/FMD2#533] opened 2021-05-09 01:35 UTC
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
GManga module is not working ever time i try to download the manga list it tell me (failed to finish: GManga: 404 not found)

**Log**
![GMmanga](https://user-images.githubusercontent.com/83671853/117557818-ade91180-b07f-11eb-9acf-258f1af4c4a7.PNG)

**Comment by Slasar41** [comment] 2021-05-14 09:07
Duplicate of #36

**Closed as completed by Slasar41** 2021-05-14 09:07 UTC
