### ISSUE TITLE
[feature request] System or fmd crash clears the downloading list.

### ISSUE THREAD

**Issue by STharanga** [dazedcat19/FMD2#123] opened 2020-09-27 08:09 UTC
**Is your feature request related to a problem? Please describe.**

After system or fmd crash the downloading list gets deleted. If you are downloading a long list of downloads or using favourites updates it will be hard to find which chapters to download again.

**Describe the solution you'd like**

Update the downloading database after download or favourite updates added.
Update the downloading database after download completed.

**Comment by dazedcat19** [comment] 2020-09-27 22:44
I need a reproducible steps for the crash to find the problem.
Download list already committed occasionally or every 10min.
Favorite list always committed after check for new chapter or when added.
The 10min timer mostly just used to store the order, it's the most consuming update iterating all items.
The reason it's not committing the data directly for every update is because it's slow on large databases. most/all people that had the problem with the databases always had a lot of items on their list. more than 15k or so. 
It's open source. You can compile it yourself with your own need.
The default commit queue is at  https://github.com/dazedcat19/FMD2/blob/588ebcb0b3b7b83b92a006d9528a49187195eeef/baseunits/SQLiteData.pas#L88

**Closed as completed** 2020-09-28 03:14 UTC

**Comment by dazedcat19** [comment] 2020-09-28 03:16
I added a flag to disable commit queue. you can compile it with `-dNO_COMMIT_QUEUE`
