### ISSUE TITLE
[bug-website module] Batoto

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [dazedcat19/FMD2#502] opened 2021-04-14 18:39 UTC
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Whenever I click on a series, the page loads the author, Genres, Status and Summary fields, but only loads the language for the title (which then gets updated on the list like that), doesn't load the cover and no chapter list is shown, which makes it impossible to download anything from there.

**Comment by Slasar41** [comment] 2021-04-15 07:27
Duplicate of https://github.com/dazedcat19/FMD2/issues/467

**Closed as completed by Slasar41** 2021-04-15 07:27 UTC
