### ISSUE TITLE
[bug-website module] Can't update batoto manually

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#602] opened 2021-06-21 13:01 UTC
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 7-64 system

**Describe the bug**
Batoto does not update manually, while I can update it from the server the manga list does not change. When I update manutally, FMD searches for directory but does not update any manga. For example: this manga isn't available in fmd batoto, https://bato.to/series/84538, but it's available on batoto itself. So, when I update, the number of the manga list does not change. 

![image](https://user-images.githubusercontent.com/24958560/122766083-f0c71780-d2c2-11eb-9b58-e828aab33876.png)
![image](https://user-images.githubusercontent.com/24958560/122766108-f7558f00-d2c2-11eb-8065-7242d7672412.png)

P.S. Ignore the title from the image, it's the manga that I want to update in Batoto.

**Comment by Mech-cyber** [comment] 2021-07-11 21:06
Same here. Moreover, any attempt to get manga's info results in its name being erased and number of chapters equal to zero:
![Безымянный2](https://user-images.githubusercontent.com/59827086/125209892-5a38b580-e2c6-11eb-9520-346349ff88c2.png)

**Comment by Slasar41** [comment] 2021-07-25 21:02
Duplicate of https://github.com/dazedcat19/FMD2/issues/467

**Closed as completed by Slasar41** 2021-07-25 21:02 UTC
