### ISSUE TITLE
[bug] Chapters unable to be obtained it always crashes

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD2#118] opened 2020-09-25 13:21 UTC
**Prerequisite**
- [x ] I'm using the latest version.
- [ ] All website modules are up to date.

- [x ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
In the latest version if chapter can not be pulled i get the error below and it says I can ignore error but it never works correctly if I ignore and continue. It has to be restarted.  Example error below from mangakakalot.com the site is up and working but the chapter could not be reached so the error below was caught.

'Program exception!
Application       : Free Manga Downloader
Version           : 2.0.26.0
Product Version   : Win64 Debug
Host Machine      : Windows 10 64-bit
FPC Version       : 3.3.1
LCL Version       : 2.1.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2020/09/24 13:36:54
Path              : C:\DOS\fmd_2.0\fmd.exe
Process ID        : 21000
MainThread ID     : 36868
Thread ID         : 14548
Time              : 25/09/2020 09:10:17.029
Sender Class      : TGetMangaInfosThread
Exception Object  : 00000000264B8D90
Exception Class   : EDatabaseError
Message           : Could not find the requested record.
  $000000010005C12C
  $000000010005C358
  $000000010005C396
  $000000010034A0B3  EXECUTE,  line 137 of ../baseunits/uGetMangaInfosThread.pas
  $000000010005BA99
  $0000000100003FB6
  $0000000100015391
  $00007FF9BDE67BD4
  $00007FF9BE42CE51'

**To Reproduce**
1. Go to mangakalot and try open chapter list

**Expected behavior**
It should not error it should have some sort of trap that if chapters can not be read terminate in so many tries/seconds.

**Additional context**
The problem happened in the old version but nowhere as often. This new release it is happening on every site where chapters can not be retrieved.

**Comment by dazedcat19** [comment] 2020-09-25 22:30
Post the url and screencap of your issue. I can't reproduce it.

**Comment by dazedcat19** [comment] 2020-09-27 23:15
Since you don't bother to reply I will close this issue.

**Closed as completed by dazedcat19** 2020-09-27 23:15 UTC
