### ISSUE TITLE
[bug] Favorites from FMD1

### ISSUE THREAD

**Issue by kurim** [dazedcat19/FMD2#66] opened 2020-07-13 21:23 UTC
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
If you convert data with not supported server the database got messed up.

**To Reproduce**
1. add a non supported Site like TenManga in my case
2. add manga to favorites
3. use converter 
4. open FMD2 check favorits

**Expected behavior**
If not supported it should be dropped

**Screenshots**
![image](https://user-images.githubusercontent.com/1880220/87354481-e18e0480-c55e-11ea-8380-7d93af678183.png)

**Comment by dazedcat19** [comment] 2020-07-14 13:27
It was intended to be left so it can be transferred to other website. right click > transfer. Or you can just bulk delete it.

**Closed as completed by dazedcat19** 2020-07-14 13:27 UTC

**Comment by kurim** [comment] 2020-07-14 17:21
Did you see what happen to save to? They all set to save 1, this should not be correct

**Comment by dazedcat19** [comment] 2020-07-14 20:54
Probably a wrong field after added a new field for persistent status. You can try the older converter from version 2.0.2. Tho that's not correct also. I'm not really supporting the converter, just my little simple script. I may delete it later. So user can convert it by their own.

**Comment by kurim** [comment] 2020-07-14 21:15
Thanks with 2.0.2 converter works fine,
now i can move to FMD 2.
