### ISSUE TITLE
[bug-website module] MangaGo has problem unable to download chapter

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD2#95] opened 2020-08-31 15:56 UTC
I already add cookies and useragent to get chapter list from MangaGo but for unknown reason, it unable to get pages list

![Untitled1](https://user-images.githubusercontent.com/40983245/91739526-9c906100-ebe4-11ea-9466-a3650ae05431.png)
![Untitled2](https://user-images.githubusercontent.com/40983245/91740234-98187800-ebe5-11ea-8f4d-7e1655bf7311.png)

**Comment by HiP1** [comment] 2020-09-12 21:17
Duplicate of #5

**Closed as completed** 2020-09-13 09:24 UTC
