### ISSUE TITLE
[bug-website module]manhuascan.com

### ISSUE THREAD

**Issue by eze15** [dazedcat19/FMD2#600] opened 2021-06-18 20:44 UTC
**Prerequisite**
- [ ] I'm using version 2.0.31.0
- [ ] All website modules are up to date.
Website is working normaly 
This isue started 13/05/21

**System information**
Windows 10 64bit

**Describe the bug**
Manngas are updates and aded to download list but fail to download this isue was firts discovered on 13/05/21 (DD/MM/YY).
The isue has continue up to the day of writting this request 18/06/21. Restarting the downloads at diferent times and diferent days has not produced any result. No tittle of this website is able to download and produces the same issue.

Name: manhuascan.com
Example: https://manhuascan.com/manga-master-villainess-the-invincible.html

[downloads db.zip](https://github.com/dazedcat19/FMD2/files/6679235/downloads.db.zip)
![Captura](https://user-images.githubusercontent.com/86129486/122614098-62515c80-d05c-11eb-9ad9-8ed4faa1e497.PNG)

**Comment by Slasar41** [comment] 2021-06-18 20:51
Duplicate of https://github.com/dazedcat19/FMD2/issues/535.

**Closed as completed by Slasar41** 2021-06-18 20:51 UTC
