### ISSUE TITLE
[bug-website module] manhuascan not working

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD2#550] opened 2021-05-25 21:19 UTC
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows-7 64 bit

**Describe the bug**
After cloudfare workaround I can access manga info but the download never starts and says failed try resuming and doesnt work.

![image](https://user-images.githubusercontent.com/24958560/119569826-16025c00-bdd1-11eb-91e9-1e236609bac7.png)
![image](https://user-images.githubusercontent.com/24958560/119569852-21558780-bdd1-11eb-9378-74e4031c4edf.png)

**Comment by Slasar41** [comment] 2021-05-26 06:45
Duplicate of https://github.com/dazedcat19/FMD2/issues/535

**Closed as completed by Slasar41** 2021-05-26 06:45 UTC
