### ISSUE TITLE
Mangasee not working[bug]

### ISSUE THREAD

**Issue by InFerNoBeasTz** [dazedcat19/FMD2#657] opened 2021-08-04 18:02 UTC
Windows 10

**Describe the bug**
When I select a manga I get a error message that says 'cannot get manga info. Please check your internet connection'. However other sites work. My Internet is fine.
![Capture](https://user-images.githubusercontent.com/52253277/128231457-98e5af6a-f497-475b-898b-a132927d3003.JPG)

**To Reproduce**
1. Go to 'Mangasee'
2. Click on 'Any manga'

**Expected behavior**
Error message pops up

**Comment by Slasar41** [comment] 2021-08-04 18:25
Duplicate of https://github.com/dazedcat19/FMD2/issues/589.

**Closed as completed by Slasar41** 2021-08-04 18:25 UTC
