### ISSUE TITLE
[bug-website module]  Yugenmangas (Does not load)

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#892] opened 2022-01-30 02:57 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

W 10 home 21h1 x64

### Describe the bug

Load the information, but do not load the chapters.

https://yugenmangas.com/series/las-50-recetas-de-te-de-la-duquesa/

**Comment by Slasar41** [comment] 2022-02-02 18:37
Duplicate of https://github.com/dazedcat19/FMD2/issues/890

**Closed by Slasar41** 2022-02-02 18:37 UTC
