### ISSUE TITLE
[bug-website module] mangaku.in change domain to mangaku.pro

### ISSUE THREAD

**Issue by hachi-zy** [dazedcat19/FMD2#588] opened 2021-06-13 06:41 UTC
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
WIN 10

**Comment by Slasar41** [comment] 2021-06-17 19:35
Duplicate of https://github.com/dazedcat19/FMD2/issues/238.

**Closed as completed by Slasar41** 2021-06-17 19:35 UTC
