### ISSUE TITLE
[bug-website module] {Yugenmangas} No load

### ISSUE THREAD

**Issue by CloudBladed** [dazedcat19/FMD2#927] opened 2022-03-12 06:08 UTC
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

W 10 21H1 x64

### Describe the bug

Load the information, but do not load the chapters.

https://yugenmangas.com/series/las-50-recetas-de-te-de-la-duquesa/

![image](https://user-images.githubusercontent.com/70826672/158006229-94c184f3-bec2-4d45-b5ee-be1ef2ca69ce.png)

Last time I opened a request with the same problem, but it was closed because it was a duplicate request without solving the real problem in question. Please clarify if it can not be done, greetings.

**Comment by Slasar41** [comment] 2022-03-13 19:29
Duplicate of https://github.com/dazedcat19/FMD2/issues/923

**Closed by Slasar41** 2022-03-13 19:29 UTC

**Comment by djgerman10** [comment] 2022-03-14 05:08
https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-JapScan
[#923](https://github.com/dazedcat19/FMD2/issues/923)
