### ISSUE TITLE
[bug] GManga  doesn't view manga list

### ISSUE THREAD

**Issue by alhatmy** [dazedcat19/FMD2#173] opened 2020-11-11 13:53 UTC
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Getting Pop-up error - Failed to finish: GManga: 404 Not Found

**To Reproduce**
1. Go to 'Manga Info'
2. Click on 'GManga' to view manga list
3. Click on 'Do you want to download manga list from the server'

**Expected behavior**
To view then download the list

**Screenshots**
![0303](https://user-images.githubusercontent.com/17156241/98819622-830e5f80-2446-11eb-931e-2c517450e784.PNG)

**Additional context**
I heard Gmanga changed the source code, but it works currently in "HakuNeko" if their code is available", just asking please ..

**Comment by Slasar41** [comment] 2020-11-11 18:10
Duplicate of https://github.com/dazedcat19/FMD2/issues/36

**Closed as completed by Slasar41** 2020-11-11 18:10 UTC
